# Test profile - H2 in-memory database
spring:
  datasource:
    url: jdbc:h2:mem:rucdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration/h2
