-- H2-compatible migration for EPP schema
CREATE TABLE epp_transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_key VARCHAR(200) NOT NULL,
  application_unique_id VARCHAR(200),
  status VARCHAR(10) NOT NULL,
  amount DECIMAL(15,2) DEFAULT 0 NOT NULL,
  email VARCHAR(100),
  raw_request CLOB,
  raw_response CLOB,
  auth_code VARCHAR(100),
  reference_no VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_epp_order_app ON epp_transaction(order_key, application_unique_id);

CREATE TABLE epp_feature_flag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(50) NOT NULL,
  enabled BOOLEAN DEFAULT TRUE NOT NULL
);
